# Generated by Django 3.2.16 on 2022-10-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranSum',
            fields=[
                ('trId', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=10, verbose_name='customerId')),
                ('code', models.CharField(max_length=10, verbose_name='memberId')),
                ('fy', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029')], max_length=9, verbose_name='fy')),
                ('againstType', models.CharField(choices=[('Shares', 'Shares'), ('Mutual Funds', 'Mutual Funds'), ('Futures & Options', 'Futures & Options'), ('Day Trading', 'Day Trading'), ('Trading', 'Trading')], max_length=20, verbose_name='type')),
                ('sp', models.CharField(max_length=5, verbose_name='scriptId')),
                ('part', models.CharField(max_length=30, verbose_name='script')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('fmr', models.FloatField(blank=True, null=True)),
                ('isinCode', models.CharField(blank=True, max_length=30, null=True)),
                ('trDate', models.DateField(verbose_name='purchaseDate')),
                ('qty', models.IntegerField(verbose_name='quantity')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=65, verbose_name='rate')),
                ('sVal', models.DecimalField(decimal_places=2, max_digits=65, verbose_name='value')),
                ('sttCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True, verbose_name='stt')),
                ('otherCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True, verbose_name='other')),
                ('noteAdd', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('marketRate', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('marketValue', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('HoldingValue', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('avgRate', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('scriptSno', models.IntegerField(blank=True, null=True)),
                ('empCode', models.CharField(blank=True, max_length=10, null=True)),
                ('clDate', models.DateField(blank=True, null=True)),
                ('clRate', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('clQTY', models.IntegerField(blank=True, null=True)),
                ('clValue', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('clsttCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('clOtherCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('balQty', models.IntegerField(blank=True, null=True)),
                ('dayTrade', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('strategyDate', models.DateField(blank=True, null=True)),
                ('strategyTrigger', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
            ],
        ),
    ]
